// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Api
{
    public partial class CheckAnswerMLModel
    {
        /// <summary>
        /// model input class for CheckAnswerMLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Recency (months)")]
            public float Recency__months_ { get; set; }

            [ColumnName(@"Frequency (times)")]
            public float Frequency__times_ { get; set; }

            [ColumnName(@"Monetary (c.c. blood)")]
            public float Monetary__c_c__blood_ { get; set; }

            [ColumnName(@"Time (months)")]
            public float Time__months_ { get; set; }

            [ColumnName(@"whether he/she donated blood in March 2007")]
            public float Whether_he_she_donated_blood_in_March_2007 { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for CheckAnswerMLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Recency (months)")]
            public float Recency__months_ { get; set; }

            [ColumnName(@"Frequency (times)")]
            public float Frequency__times_ { get; set; }

            [ColumnName(@"Monetary (c.c. blood)")]
            public float Monetary__c_c__blood_ { get; set; }

            [ColumnName(@"Time (months)")]
            public float Time__months_ { get; set; }

            [ColumnName(@"whether he/she donated blood in March 2007")]
            public uint Whether_he_she_donated_blood_in_March_2007 { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("CheckAnswerMLModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
